### PR TITLE
Make sure you capture variables bound in PFieldPun

### PR DESCRIPTION
**Pull request by ndmitchell**
Not doing so leads to the bug reported at https://github.com/ndmitchell/hlint/issues/619

### CODE REVIEW

**Comment by ndmitchell** [comment]
I also removed a comment on `PWildcard` - I think we'd assumed it was `{..}` when PWildcard is actually `_`.

**Review by pepeiborra — APPROVED** [review]

**Comment by ndmitchell** [comment]
Thanks, can we get a release with the fix included?

**Comment by pepeiborra** [comment]
Released 0.2.5

**Comment by ndmitchell** [comment]
Thanks! I owe you a beer 🍺

**Pull request merged**
